[2023-12-25T13:12:49.166+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-07-17T00:00:00+00:00 [queued]>
[2023-12-25T13:12:50.890+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-07-17T00:00:00+00:00 [queued]>
[2023-12-25T13:12:50.890+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-25T13:12:52.099+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): Extract> on 2023-07-17 00:00:00+00:00
[2023-12-25T13:12:52.196+0000] {standard_task_runner.py:60} INFO - Started process 429 to run task
[2023-12-25T13:12:54.978+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'traffic_flow', 'Extract', 'scheduled__2023-07-17T00:00:00+00:00', '--job-id', '490', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp45gf3pj2']
[2023-12-25T13:13:00.265+0000] {standard_task_runner.py:88} INFO - Job 490: Subtask Extract
[2023-12-25T13:13:00.642+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-25T13:13:00.908+0000] {task_command.py:423} INFO - Running <TaskInstance: traffic_flow.Extract scheduled__2023-07-17T00:00:00+00:00 [running]> on host b33131cfaa7f
[2023-12-25T13:13:50.192+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2023-12-25T13:13:53.346+0000] {process_utils.py:131} INFO - Sending 15 to group 429. PIDs of all processes in the group: [429]
[2023-12-25T13:13:54.535+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 429
