[2023-12-25T13:12:49.169+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-07-15T00:00:00+00:00 [queued]>
[2023-12-25T13:12:50.900+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: traffic_flow.Extract scheduled__2023-07-15T00:00:00+00:00 [queued]>
[2023-12-25T13:12:50.900+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-25T13:12:52.127+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): Extract> on 2023-07-15 00:00:00+00:00
[2023-12-25T13:12:52.197+0000] {standard_task_runner.py:60} INFO - Started process 430 to run task
[2023-12-25T13:12:57.810+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'traffic_flow', 'Extract', 'scheduled__2023-07-15T00:00:00+00:00', '--job-id', '499', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpayxwu9uo']
[2023-12-25T13:13:00.526+0000] {standard_task_runner.py:88} INFO - Job 499: Subtask Extract
[2023-12-25T13:13:00.769+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-25T13:13:01.188+0000] {task_command.py:423} INFO - Running <TaskInstance: traffic_flow.Extract scheduled__2023-07-15T00:00:00+00:00 [running]> on host b33131cfaa7f
[2023-12-25T13:13:50.193+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2023-12-25T13:13:53.379+0000] {process_utils.py:131} INFO - Sending 15 to group 430. PIDs of all processes in the group: [430]
[2023-12-25T13:13:54.538+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 430
